---
- name: Install MySQL exporter
  apt:
    name: prometheus-mysqld-exporter
    force_apt_get: yes

- name: Install PyMySQL
  apt:
    name: python3-pymysql
    force_apt_get: yes

- name: making mysql config file
   copy:
     dest: /etc/mysql/mysql.conf.d/override.cnf
     content: |
      [mysqld]
      bind-address = 8.8.8.8
      
- name: Copy .my.cnf
  template:
    src: .my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify: Restart MySQL exporter

- name: Create MySQL user
  mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    host: "%"

- name: Make sure MySQL exporter is enabled
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
