---
- name: Install HAProxy
  apt:
    name: haproxy
    state: latest

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

#- name: Install HAProxy exporter
#  apt:
#    name: haproxy_exporter
#    state: latest

- name: HAProxy Exporter
  docker_container:
    name: haproxy_exporter
    image: quay.io/prometheus/haproxy-exporter:v0.9.0
    ports:
      - "9101:9101"
    command: --haproxy.scrape-uri="http://{{ inventory_hostname }}:88/haproxy?stats;csv"
    restart_policy: always

- name: start HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes

# Before starting the service - run handlers

- name: Execute handlers preemptively
  meta: flush_handlers

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Check if the service is started and if it is not, start it
  service:
    name: haproxy
    state: restarted
    enabled: yes
