---
 - name: ensure nginx is at the latest version
   apt:
     name: nginx

 - name: start nginx
   service:
      name: nginx
      state: started

 - name: Configure reverse proxy
   template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    force: yes

 - name: restart nginx
   service:
      name: nginx
      state: restarted
   become: yes
