- name: Prometheus
  hosts: internal
  become: yes
  roles:
    - prometheus

- name: DNS
  hosts: dns_server
  become: yes
  gather_facts: no
  roles:
    - bind_exporter

- name: Nginx Exporter
  hosts: application
  become: yes
  gather_facts: no
  roles:
    - nginx_exporter
