---
 - name: installing package bind9
   apt:
     name: bind9

 - name: Copy named conf file
   template:
     src: named.conf.options.j2
     dest: /etc/named.conf.options
     owner: root
     group: named
     mode: 0660
   notify: restart named

 - name: Make named directory
   file:
     path: /etc/named
     state: directory
     owner: root
     group: named
     mode: 0750

 - name: Copy named conf local file
   template:
     src: resolv.conf
     dest: /etc/named/resolv.conf
     owner: root
     group: named
     mode: 0640
   notify: restart named


 - name: Make zones Directory
   file:
     path: /etc/named/zones
     state: directory
     owner: root
     group: named
     mode: 0750

 - name: Copy forward file
   template:
     src: db.adattiva.j2
     dest: /etc/named/zones/db.{{ domain }}
     owner: root
     group: named
     mode: 0640
   notify: restart named

 - name: Open firewall port
   firewalld:
     service: dns
     permanent: true
     state: enabled
     immediate: yes