---
 - name: creating user agama
   user: 
     name: agama

 - name: creating directory /opt/agama
   file:
     path: /opt/agama
     state: directory
     owner: agama

 - name: installing dependencies
   apt:
     name: python3-flask-sqlalchemy


 - name: installing agama
   get_url:
     url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
     dest: /opt/agama/agama.py