---
- name: Install Prometheus
  apt:
    name: 
      - prometheus
    force_apt_get: yes
    
- name: Add the user prometheus
  user:
    name: prometheus
    group: root
    
- name: Configure Prometheus
  template: 
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
  notify: Restart Prometheus

- name: Make prometheus available
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    owner: prometheus
  notify: Restart Prometheus
