---
- name: Install Docker
  apt:
    name: docker.io
  
- name: Install Docker-Compose
  apt:
    name: docker-compose
  
- name: Install Python Module
  apt:
    name: python3-pip
  
- name: Install Python Docker-Compose
  pip:
    name: docker-compose
  
#- name: Install Docker package
 # apt:
  #  name:
   #   - python3-docker
    #  - docker.io
     # - python36-docker
      #- docker-componse 
    #force_apt_get: yes  

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes
    
    
