---
 - name: installing package uwsgi
   apt:
     name: uwsgi

 - name: installing package uwsgi-plugin-python3
   apt:
     name: uwsgi-plugin-python3

 - name: create config file
   file:
     path: /etc/uwsgi/apps-enabled/agama.ini
     state: touch
     remote_src: yes

 - name: making uwsgi config file
   copy:
     dest: /etc/uwsgi/apps-enabled/agama.ini
     content: |
      [uwsgi]
      chdir = /opt/agama/
      module = agama:app
      env = AGAMA_DATABASE_URI=sqlite:////opt/agama/test.sqlite3
      socket = localhost:5000
      uid = agama

 - name: restarting
   service:
     name: uwsgi
     state: restarted

 - name: configuring to start on boot
   service:
     name: uwsgi
     state: started
   become: true
   become_user: agama