---
 - name: installing package mysql-server
   apt:
     name: mysql-server

 - name: installing package python3-pymysql
   apt:
     name: python3-pymysql

 - name: making mysql config file
   copy:
     dest: /etc/mysql/mysql.conf.d/override.cnf
     content: |
      [mysqld]
      bind-address = 0.0.0.0

 - name: creating database
   community.mysql.mysql_db:
     name: mysql_database
     state: present

 - name: MySQL database
   mysql_db:
     name: "{{ mysql_database }}"
     login_unix_socket: /var/run/mysqld/mysqld.sock

 - name: restarting
   service:
     name: mysql
     state: restarted

 - name: configuring to start on boot
   service:
     name: mysql
     state: started
   become: true