---
 - name: Install Bind9 and dnspython
   apt:
     name:
       - bind9
       - python3-dnspython
     state: latest
     force_apt_get: no


 - name: Bind configuration
   template:
     src: named.conf.options.j2
     dest: /etc/bind/named.conf.options
     validate: named-checkconf %s
   notify: Restart bind9



 - name: Bind zones configuration
   template:
     src: named.conf.local.j2
     dest: /etc/bind/named.conf.local
   notify: Restart bind9


 - name: Configure master zone
   template:
     src: db.cloud.j2
     dest: /var/lib/bind/db.{{ domain }}
     force: no
   notify: Rndc reload
   when: inventory_hostname in groups['dns_masters']


 - name: copy the resolv file
   template:
     src: resolv.conf.j2
     dest: /etc/resolv.conf
   notify: Restart bind9


 - name: Execute handlers before adding records
   meta: flush_handlers


 - name: Start service bind9, if not started
   service:
     name: bind9
     state: started
     enabled: yes


 - name: Add A record
   nsupdate:
     key_algorithm: "hmac-sha256"
     key_name: "{{ dns_update }}"
     key_secret: "{{ dns_update_key | string }}"
     server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
     zone: "{{ domain }}"
     record: A
     value:
     type: "A"
   when: inventory_hostname == groups['dns_masters'][0]
   vars:
     ns_transfer_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32323536323731663433313538656631383739313436363732623730386630376365663536306436
          3234316466376436366233616433623434353764373330300a313261396166343966663865653235
          36623861376233646435313236383039346437626662633635346366313163656335373533363537
          3333336638663266320a643439386633346363366233383365616638636563613538393661613238
          31393331666135653539353335383631363663653838326235313233623031613537333766393034
          6235643965643738313465313465613766316631363138373335
          
 - name: Add CNAME record
   nsupdate:
     key_algorithm: "hmac-sha256"
     key_name: "{{ dns_update }}"
     key_secret: "{{ dns_update_key }}"
     server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
     zone: "{{ domain }}"
     record: "{{ item['cname'] }}.{{ domain }}."
     value: "{{ item['real'] }}.{{ domain }}."
     type: "CNAME"
   loop: "{{ dns_cnames }}"
   when: inventory_hostname == groups['dns_masters'][0]

 - name: Force all notified handlers to run at this point, not waiting for normal sync points
   meta: flush_handlers




 - name: Start service bind9, if not started
   service:
     name: bind9
     state: started
     enabled: yes

